import { Container } from "@mui/material";
import Head from "next/head";
import { ReactNode } from "react";

export default function DefaultLayout({
  children,
  title,
}: {
  children: ReactNode;
  title: string;
}) {
  return (
    <>
      <Head>
        <title> {title || "Loading"} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth={false}>{children}</Container>
    </>
  );
}
